import { EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { SaRadioGroupService } from './sa-radio-group.service';
import * as i0 from "@angular/core";
export type RadioSize = 'sm' | 'md' | 'lg';
export type RadioStatus = 'default' | 'success' | 'error';
export declare class SaRadioComponent implements ControlValueAccessor, OnInit, OnDestroy {
    private radioGroupService;
    value: any;
    size: RadioSize;
    status: RadioStatus;
    label: string;
    private _noLabel;
    set noLabel(value: boolean | any);
    get noLabel(): boolean;
    private _hideLabel;
    set hideLabel(value: boolean | any);
    get hideLabel(): boolean;
    helperText: string;
    errorText: string;
    required: boolean;
    disabled: boolean;
    readonly: boolean;
    id: string;
    name: string;
    class: string;
    valueChange: EventEmitter<any>;
    change: EventEmitter<Event>;
    focus: EventEmitter<FocusEvent>;
    blur: EventEmitter<FocusEvent>;
    selectedValue: any;
    isFocused: boolean;
    private _generatedId;
    private subscription;
    private onChange;
    private onTouched;
    get hostClasses(): string;
    constructor(radioGroupService: SaRadioGroupService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    get radioId(): string;
    get isChecked(): boolean;
    get radioClasses(): string;
    get labelClasses(): string;
    get shouldShowLabel(): boolean;
    get containerClasses(): string;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    onRadioChange(event: Event): void;
    onRadioFocus(event: FocusEvent): void;
    onRadioBlur(event: FocusEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SaRadioComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SaRadioComponent, "sa-radio", never, { "value": { "alias": "value"; "required": false; }; "size": { "alias": "size"; "required": false; }; "status": { "alias": "status"; "required": false; }; "label": { "alias": "label"; "required": false; }; "noLabel": { "alias": "noLabel"; "required": false; }; "hideLabel": { "alias": "hideLabel"; "required": false; }; "helperText": { "alias": "helperText"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "id": { "alias": "id"; "required": false; }; "name": { "alias": "name"; "required": false; }; "class": { "alias": "class"; "required": false; }; }, { "valueChange": "valueChange"; "change": "change"; "focus": "focus"; "blur": "blur"; }, never, never, false, never>;
}
