import { EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export type TextareaSize = 'sm' | 'md' | 'lg';
export type TextareaStatus = 'default' | 'success' | 'error';
export declare class SaTextareaComponent implements ControlValueAccessor {
    value: string;
    size: TextareaSize;
    status: TextareaStatus;
    label: string;
    private _noLabel;
    set noLabel(value: boolean | any);
    get noLabel(): boolean;
    placeholder: string;
    helperText: string;
    errorText: string;
    required: boolean;
    readonly: boolean;
    disabled: boolean;
    id: string;
    name: string;
    rows: number;
    cols: number;
    minlength: number | null;
    maxlength: number | null;
    resize: 'none' | 'both' | 'horizontal' | 'vertical';
    height: number | null;
    valueChange: EventEmitter<string>;
    focus: EventEmitter<FocusEvent>;
    blur: EventEmitter<FocusEvent>;
    isFocused: boolean;
    private onChange;
    private onTouched;
    get textareaClasses(): string;
    get labelClasses(): string;
    get shouldShowLabel(): boolean;
    get textareaStyles(): any;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    onModelChange(value: string): void;
    onTextareaFocus(event: FocusEvent): void;
    onTextareaBlur(event: FocusEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SaTextareaComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SaTextareaComponent, "sa-textarea", never, { "value": { "alias": "value"; "required": false; }; "size": { "alias": "size"; "required": false; }; "status": { "alias": "status"; "required": false; }; "label": { "alias": "label"; "required": false; }; "noLabel": { "alias": "noLabel"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "helperText": { "alias": "helperText"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "id": { "alias": "id"; "required": false; }; "name": { "alias": "name"; "required": false; }; "rows": { "alias": "rows"; "required": false; }; "cols": { "alias": "cols"; "required": false; }; "minlength": { "alias": "minlength"; "required": false; }; "maxlength": { "alias": "maxlength"; "required": false; }; "resize": { "alias": "resize"; "required": false; }; "height": { "alias": "height"; "required": false; }; }, { "valueChange": "valueChange"; "focus": "focus"; "blur": "blur"; }, never, never, false, never>;
}
