import { Component, Input } from '@angular/core';
import { IconDefinition, findIconDefinition, IconName } from '@fortawesome/fontawesome-svg-core';
import { 
  faSpinner, 
  faDownload, 
  faTrash, 
  faShare, 
  faPrint, 
  faHeart,
  faHome,
  faUser,
  faCog,
  faSearch,
  faStar,
  faEdit,
  faSave,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendar,
  faClock,
  faInfo,
  faExclamationTriangle,
  faQuestion,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faPencil,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleRight,
  // Nuevos iconos agregados
  faThLarge,
  faUsers,
  faLink,
  faCopy,
  faUniversalAccess,
  faRunning,
  faImage,
  faCalendarAlt,
  faChartBar,
  faChartLine,
  faAppleAlt,
  faRobot,
  faGift,
  faShoppingBag,
  faBalanceScale,
  faBatteryThreeQuarters,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faBellSlash,
  faBicycle,
  faBookmark,
  faBowlFood,
  faBox,
  faBus,
  faBirthdayCake,
  faCalculator,
  faCalendarDay,
  faCamera,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faFile,
  faChartPie,
  faComments,
  faFlask,
  faMicroscope,
  faCookieBite,
  faSprayCan,
  faSoap,
  faExpand,
  faCloud,
  faCoffee,
  faComment,
  faCreditCard,
  faCrop,
  faCropAlt,
  faTruck,
  faFileUpload,
  faEllipsisH,
  faPlane,
  faGraduationCap,
  faEquals,
  faEraser,
  faFileExcel,
  faFileDownload,
  faSignOutAlt,
  faSmile,
  faFrown,
  faMask,
  faMedal,
  faBoxOpen,
  faSeedling,
  faFilter,
  faFingerprint,
  faFire,
  faTrophy,
  faFish,
  faFlag,
  faForward,
  faVolumeUp,
  faExpandArrowsAlt,
  faVolumeMute,
  faBars,
  faBriefcase,
  faMicrochip,
  faHeartbeat,
  faHistory,
  faMicrophone,
  faIceCream,
  faLightbulb,
  faKey,
  faLaptop,
  faLayerGroup,
  faListUl,
  faVolumeDown,
  faMapPin,
  faLocationArrow,
  faLocationDot,
  faGlobe,
  faCompass,
  faPills,
  faMobile,
  faMobileAlt,
  faMoneyBill,
  faMotorcycle,
  faStickyNote,
  faEllipsisV,
  faLungs,
  faCashRegister,
  faPaperPlane,
  faPaperclip,
  faDesktop,
  faPause,
  faPercent,
  faPiggyBank,
  faPlay,
  faMousePointer,
  faSwimmingPool,
  faBan,
  faTag,
  faShield,
  faQrcode,
  faReceipt,
  faRedo,
  faRuler,
  faUtensils,
  faTshirt,
  faShoppingCart,
  faSlidersH,
  faGlassWhiskey,
  faSort,
  faTachometerAlt,
  faSpoon,
  faStarHalf,
  faStop,
  faStore,
  faThermometerHalf,
  faThumbsDown,
  faThumbsUp,
  faBolt,
  faTicketAlt,
  faSitemap,
  faBath,
  faUndo,
  faUpload,
  faUserPlus,
  faUserMinus,
  faVideo,
  faExclamationCircle,
  faWifi,
  faTable,
  faTablet,
  faTabletAlt,
  faAmbulance
} from '@fortawesome/free-solid-svg-icons';

export type IconSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'sa-icon',
  templateUrl: './sa-icon.component.html',
  styleUrl: './sa-icon.component.scss'
})
export class SaIconComponent {
  // Propiedades con setters/getters para flexibilidad máxima
  private _name: string = '';
  private _color: string = '#000000';
  private _size: IconSize = 'md';

  @Input()
  set name(value: string | any) {
    this._name = value || '';
  }
  get name(): string {
    return this._name;
  }

  @Input()
  set color(value: string | any) {
    this._color = value || '#000000';
  }
  get color(): string {
    return this._color;
  }

  @Input()
  set size(value: IconSize | any) {
    this._size = value || 'md';
  }
  get size(): IconSize {
    return this._size;
  }

  // Método para obtener el icono basado en el string
  get iconDefinition(): IconDefinition | undefined {
    if (!this.name) return undefined;
    
    // Mapeo local de iconos (más rápido)
    const localIconMap: { [key: string]: IconDefinition } = {
      // Iconos básicos (solid por defecto)
      'spinner': faSpinner,
      'download': faDownload,
      'trash': faTrash,
      'share': faShare,
      'print': faPrint,
      'heart': faHeart,
      'home': faHome,
      'user': faUser,
      'cog': faCog,
      'search': faSearch,
      'star': faStar,
      'edit': faEdit,
      'save': faSave,
      'plus': faPlus,
      'minus': faMinus,
      'check': faCheck,
      'times': faTimes,
      'eye': faEye,
      'eye-slash': faEyeSlash,
      'lock': faLock,
      'unlock': faUnlock,
      'bell': faBell,
      'envelope': faEnvelope,
      'phone': faPhone,
      'map-marker-alt': faMapMarkerAlt,
      'calendar': faCalendar,
      'clock': faClock,
      'info': faInfo,
      'exclamation-triangle': faExclamationTriangle,
      'question': faQuestion,
      'chevron-down': faChevronDown,
      'chevron-up': faChevronUp,
      'chevron-left': faChevronLeft,
      'chevron-right': faChevronRight,
      'arrow-left': faArrowLeft,
      'arrow-right': faArrowRight,
      'arrow-up': faArrowUp,
      'arrow-down': faArrowDown,
      'pencil': faPencil,
      'angle-double-left': faAngleDoubleLeft,
      'angle-left': faAngleLeft,
      'angle-right': faAngleRight,
      'angle-double-right': faAngleDoubleRight,
      'table': faTable,
      'th-large': faThLarge,
      'users': faUsers,
      'universal-access': faUniversalAccess,
      'running': faRunning,
      'image': faImage,
      'calendar-alt': faCalendarAlt,
      'chart-line': faChartLine,
      'apple-alt': faAppleAlt,
      'robot': faRobot,
      'shopping-bag': faShoppingBag,
      'balance-scale': faBalanceScale,
      'battery-three-quarters': faBatteryThreeQuarters,
      'battery-quarter': faBatteryQuarter,
      'battery-empty': faBatteryEmpty,
      'bell-slash': faBellSlash,
      'bookmark': faBookmark,
      'bowl-food': faBowlFood,
      'box': faBox,
      'bus': faBus,
      'birthday-cake': faBirthdayCake,
      'calendar-day': faCalendarDay,
      'file': faFile,
      'flask': faFlask,
      'cookie-bite': faCookieBite,
      'spray-can': faSprayCan,
      'soap': faSoap,
      'expand': faExpand,
      'cloud': faCloud,
      'comment': faComment,
      'file-upload': faFileUpload,
      'ellipsis-h': faEllipsisH,
      'plane': faPlane,
      'graduation-cap': faGraduationCap,
      'file-excel': faFileExcel,
      'sign-out-alt': faSignOutAlt,
      'smile': faSmile,
      'frown': faFrown,
      'mask': faMask,
      'box-open': faBoxOpen,
      'seedling': faSeedling,
      'volume-up': faVolumeUp,
      'expand-arrows-alt': faExpandArrowsAlt,
      'volume-mute': faVolumeMute,
      'bars': faBars,
      'briefcase': faBriefcase,
      'microchip': faMicrochip,
      'heartbeat': faHeartbeat,
      'history': faHistory,
      'microphone': faMicrophone,
      'lightbulb': faLightbulb,
      'key': faKey,
      'layer-group': faLayerGroup,
      'list-ul': faListUl,
      'volume-down': faVolumeDown,
      'pills': faPills,
      'mobile': faMobile,
      'mobile-alt': faMobileAlt,
      'money-bill': faMoneyBill,
      'sticky-note': faStickyNote,
      'ellipsis-v': faEllipsisV,
      'lungs': faLungs,
      'cash-register': faCashRegister,
      'paper-plane': faPaperPlane,
      'desktop': faDesktop,
      'package': faBox,
      'chart-pie': faChartPie,
      'mouse-pointer': faMousePointer,
      'swimming-pool': faSwimmingPool,
      'ban': faBan,
      'tag': faTag,
      'shield': faShield,
      'qrcode': faQrcode,
      'redo': faRedo,
      'ruler': faRuler,
      'utensils': faUtensils,
      'tshirt': faTshirt,
      'sliders-h': faSlidersH,
      'glass-whiskey': faGlassWhiskey,
      'sort': faSort,
      'tachometer-alt': faTachometerAlt,
      'spoon': faSpoon,
      'store': faStore,
      'tablet': faTablet,
      'tablet-alt': faTabletAlt,
      'thermometer-half': faThermometerHalf,
      'bolt': faBolt,
      'ticket-alt': faTicketAlt,
      'sitemap': faSitemap,
      'bath': faBath,
      
      // Nuevos iconos agregados
      'cell': faDesktop,
      'grid': faThLarge,
      'group': faUsers,
      'link': faLink,
      'copy': faCopy,
      'accessibility-alt': faUniversalAccess,
      'accessibility': faUniversalAccess,
      'activity': faRunning,
      'add-document': faFile,
      'add-image': faImage,

      'analytics': faChartBar,
      'analytics-raise': faChartLine,
      'apple': faAppleAlt,
      'assistant': faRobot,
      'bag-of-flour': faGift,
      'bag-with-gift': faGift,
      'bags': faShoppingBag,
      'balance': faBalanceScale,
      'battery-alt': faBatteryThreeQuarters,
      'battery-charginig': faBatteryHalf,
      'battery-full': faBatteryHalf,
      'battery-half': faBatteryHalf,
      'battery-low': faBatteryQuarter,
      'bell-new-message': faBell,
      'bell-off': faBellSlash,
      'bicycle': faBicycle,
      'bookmark-simple': faBookmark,
      'bowl': faBowlFood,

      'bus-front': faBus,
      'butter': faBirthdayCake,
      'cake': faBirthdayCake,
      'calculator': faCalculator,
      'calendar-history-alt': faCalendarDay,
      'calendar-history': faCalendarDay,

      'camera': faCamera,

      'candy': faCookieBite,
      'caret-down': faCaretDown,
      'caret-left': faCaretLeft,
      'caret-right': faCaretRight,
      'caret-up': faCaretUp,
      'cells-document': faFile,
      'chart-bar': faChartBar,
      'chart-pie-slice': faChartPie,
      'chat-circle-text': faComments,
      'chemical-experiment': faFlask,
      'chemical-test': faMicroscope,
      'chocolate-bar': faCookieBite,
      'cleaner': faSprayCan,
      'cleaner-dispenser': faSoap,
      'close-full-screen': faExpand,
      'cloud-offline': faCloud,
      'cloud-problem': faCloud,
      'coffee': faCoffee,
      'comments': faComment,
      'cookie': faCookieBite,
      'credit-card': faCreditCard,
      'crop-alt': faCropAlt,
      'crop': faCrop,
      'crop-health': faCrop,
      'delivery-guy': faTruck,
      'density': faDesktop,
      'detergent': faSoap,
      'document-upload': faFileUpload,
      'dots-three': faEllipsisH,
      'download-alt': faDownload,
      'dron': faPlane,
      'education': faGraduationCap,
      'envelope-new-message': faEnvelope,
      'equals': faEquals,
      'eraser': faEraser,
      'excel': faFileExcel,
      'excel-download': faFileDownload,
      'exit': faSignOutAlt,
      'face-satisfied': faSmile,
      'face-dissatisfied': faFrown,
      'face-mask': faMask,
      'facebook': faShare,
      'fast-truck': faTruck,

      'favorite-medal': faMedal,
      'favorite-package': faBoxOpen,
      'feeder': faSeedling,
      'file-download': faFileDownload,
      'filter': faFilter,
      'fingerprint': faFingerprint,
      'fire': faFire,
      'fireworks': faFire,
      'first-place': faTrophy,
      'fish': faFish,
      'flag': faFlag,
      'forward': faForward,
      'full-volume': faVolumeUp,
      'full-screen': faExpandArrowsAlt,
      'gear': faCog,
      'gift': faGift,
      'gift-delivery': faGift,
      'globe': faGlobe,
      'group-bigger': faUsers,
      'half-volume': faVolumeMute,
      'hamburger': faBars,
      'handbag': faBriefcase,
      'happy-chip': faMicrochip,
      'healthy': faHeartbeat,
      'history-time': faHistory,
      'hydrophone': faMicrophone,
      'ice-cream': faIceCream,
      'idea': faLightbulb,

      'instagram': faShare,
      'intelligence-a-i': faRobot,
      'laptop': faLaptop,
      'layer': faLayerGroup,
      'list-bulleted': faListUl,
      'load-balancer-classic': faDesktop,
      'low-volume': faVolumeDown,
      'machine-learning-model': faRobot,
      'magnifying-glass': faSearch,
      'map': faGlobe,
      'map-pin': faMapPin,
      'map-marker': faMapMarkerAlt,
      'location': faLocationDot,
      'location-pin': faMapPin,
      'location-arrow': faLocationArrow,
      'location-dot': faLocationDot,
      'compass': faCompass,
      'navigation': faCompass,
      'maps': faGlobe,
      'medal': faMedal,
      'medicine-alert': faExclamationTriangle,
      'medicine': faPills,
      'micro-chip-alt': faMicrochip,
      'micro-chip': faMicrochip,
      'microscope': faMicroscope,
      'mobile-horizontal': faMobile,
      'mobile-vertical': faMobileAlt,
      'money': faMoneyBill,
      'motorcycle': faMotorcycle,
      'note-pencil': faStickyNote,
      'openlock': faUnlock,
      'overflow-menu-vertical': faEllipsisV,
      'oxygen': faLungs,
      'p-o-s': faCashRegister,

      'paper-plane-right': faPaperPlane,
      'paperclip': faPaperclip,
      'parallel-screen': faDesktop,

      'pause': faPause,
      'percent': faPercent,


      'piggy-bank': faPiggyBank,
      'pill': faPills,
      'place-location': faMapMarkerAlt,
      'play': faPlay,
      'pointer': faMousePointer,
      'pointer-lock': faMousePointer,
      'pool-ladder': faSwimmingPool,
      'post-history': faHistory,
      'postit': faStickyNote,
      'prohibit': faBan,
      'promotion': faTag,
      'protection-checked': faShield,
      'qr': faQrcode,
      'receipt': faReceipt,
      'receipt-checked': faReceipt,

      'renew': faRedo,
      'repeat': faRedo,
      'repeat-purchase': faRedo,
      'ruc': faUser,
      'ruler-alt': faRuler,
      'sauce': faUtensils,
      'scan': faQrcode,
      'search-layers': faSearch,
      'sensor': faMicrochip,
      'settings-alt': faCog,
      'share-network': faShare,
      'shirt': faTshirt,
      'shopping-cart': faShoppingCart,
      'shrimp': faFish,
      'sign-out': faSignOutAlt,
      'sliders-horizontal': faSlidersH,
      'soda': faGlassWhiskey,
      'sort-by': faSort,
      'soup-dispenser': faUtensils,
      'soup-noodles': faUtensils,
      'speedometer': faTachometerAlt,
      'sponge': faSpoon,
      'star-half': faStarHalf,
      'stop': faStop,
      'storefront': faStore,
      'styling-cream': faSoap,
      'substract-volume': faVolumeMute,
      'tablet-horizontal': faDesktop,
      'tablet-vertical': faDesktop,
      'temperature': faThermometerHalf,
      'thumbs-down': faThumbsDown,
      'thumbs-up': faThumbsUp,
      'thunder': faBolt,
      'ticket': faTicketAlt,
      'toothpaste': faSoap,
      'tree-view': faSitemap,
      'trend-down': faChartLine,
      'trend-up': faChartLine,
      'trophy': faTrophy,
      'truck': faTruck,
      'tub': faBath,
      'twitter': faShare,
      'undo': faUndo,
      'upload': faUpload,
      'user-avatar': faUser,
      'user-add': faUserPlus,
      'user-plus': faUserPlus,
      'user-substract': faUserMinus,
      'user-minus': faUserMinus,
      'user-with-cart': faUser,
      'video': faVideo,
      'video-layer': faVideo,
      'exclamation-circle': faExclamationCircle,
      'warning-circle': faExclamationCircle,
      'warning-triangle': faExclamationTriangle,
      'whatsapp': faShare,
      'wifi': faWifi,
      'wi-fi': faWifi,
      'wi-fi-off': faWifi,
      'x': faTimes,
      'youtube': faShare,
      
      // También soporta formato fas fa-
      'fas fa-spinner': faSpinner,
      'fas fa-download': faDownload,
      'fas fa-trash': faTrash,
      'fas fa-share': faShare,
      'fas fa-print': faPrint,
      'fas fa-heart': faHeart,
      'fas fa-home': faHome,
      'fas fa-user': faUser,
      'fas fa-cog': faCog,
      'fas fa-search': faSearch,
      'fas fa-star': faStar,
      'fas fa-edit': faEdit,
      'fas fa-save': faSave,
      'fas fa-plus': faPlus,
      'fas fa-minus': faMinus,
      'fas fa-check': faCheck,
      'fas fa-times': faTimes,
      'fas fa-eye': faEye,
      'fas fa-eye-slash': faEyeSlash,
      'fas fa-lock': faLock,
      'fas fa-unlock': faUnlock,
      'fas fa-bell': faBell,
      'fas fa-envelope': faEnvelope,
      'fas fa-phone': faPhone,
      'fas fa-map-marker-alt': faMapMarkerAlt,
      'fas fa-map-pin': faMapPin,
      'fas fa-location-arrow': faLocationArrow,
      'fas fa-location-dot': faLocationDot,
      'fas fa-compass': faCompass,
      'fas fa-globe': faGlobe,
      'fas fa-calendar': faCalendar,
      'fas fa-clock': faClock,
      'fas fa-info': faInfo,
      'fas fa-exclamation-triangle': faExclamationTriangle,
      'fas fa-question': faQuestion,
      'fas fa-chevron-down': faChevronDown,
      'fas fa-chevron-up': faChevronUp,
      'fas fa-chevron-left': faChevronLeft,
      'fas fa-chevron-right': faChevronRight,
      'fas fa-arrow-left': faArrowLeft,
      'fas fa-arrow-right': faArrowRight,
      'fas fa-arrow-up': faArrowUp,
      'fas fa-arrow-down': faArrowDown,
      'fas fa-pencil': faPencil,
      'fas fa-user-plus': faUserPlus,
      'fas fa-user-minus': faUserMinus,
      'fas fa-video': faVideo,
      'fas fa-exclamation-circle': faExclamationCircle,
      'fas fa-wifi': faWifi,
      'fas fa-table': faTable,
      'fas fa-th-large': faThLarge,
      'fas fa-users': faUsers,
      'fas fa-universal-access': faUniversalAccess,
      'fas fa-running': faRunning,
      'fas fa-image': faImage,
      'fas fa-calendar-alt': faCalendarAlt,
      'fas fa-chart-line': faChartLine,
      'fas fa-apple-alt': faAppleAlt,
      'fas fa-robot': faRobot,
      'fas fa-shopping-bag': faShoppingBag,
      'fas fa-balance-scale': faBalanceScale,
      'fas fa-battery-three-quarters': faBatteryThreeQuarters,
      'fas fa-battery-quarter': faBatteryQuarter,
      'fas fa-battery-empty': faBatteryEmpty,
      'fas fa-bell-slash': faBellSlash,
      'fas fa-bookmark': faBookmark,
      'fas fa-bowl-food': faBowlFood,
      'fas fa-box': faBox,
      'fas fa-bus': faBus,
      'fas fa-birthday-cake': faBirthdayCake,
      'fas fa-calendar-day': faCalendarDay,
      'fas fa-file': faFile,
      'fas fa-flask': faFlask,
      'fas fa-cookie-bite': faCookieBite,
      'fas fa-spray-can': faSprayCan,
      'fas fa-soap': faSoap,
      'fas fa-expand': faExpand,
      'fas fa-cloud': faCloud,
      'fas fa-comment': faComment,
      'fas fa-file-upload': faFileUpload,
      'fas fa-ellipsis-h': faEllipsisH,
      'fas fa-plane': faPlane,
      'fas fa-graduation-cap': faGraduationCap,
      'fas fa-file-excel': faFileExcel,
      'fas fa-sign-out-alt': faSignOutAlt,
      'fas fa-smile': faSmile,
      'fas fa-frown': faFrown,
      'fas fa-mask': faMask,
      'fas fa-box-open': faBoxOpen,
      'fas fa-seedling': faSeedling,
      'fas fa-volume-up': faVolumeUp,
      'fas fa-expand-arrows-alt': faExpandArrowsAlt,
      'fas fa-volume-mute': faVolumeMute,
      'fas fa-bars': faBars,
      'fas fa-briefcase': faBriefcase,
      'fas fa-microchip': faMicrochip,
      'fas fa-heartbeat': faHeartbeat,
      'fas fa-history': faHistory,
      'fas fa-microphone': faMicrophone,
      'fas fa-lightbulb': faLightbulb,
      'fas fa-key': faKey,
      'fas fa-layer-group': faLayerGroup,
      'fas fa-list-ul': faListUl,
      'fas fa-volume-down': faVolumeDown,
      'fas fa-pills': faPills,
      'fas fa-mobile': faMobile,
      'fas fa-mobile-alt': faMobileAlt,
      'fas fa-money-bill': faMoneyBill,
      'fas fa-sticky-note': faStickyNote,
      'fas fa-ellipsis-v': faEllipsisV,
      'fas fa-lungs': faLungs,
      'fas fa-cash-register': faCashRegister,
      'fas fa-paper-plane': faPaperPlane,
      'fas fa-desktop': faDesktop,
      'fas fa-package': faBox,
      'fas fa-chart-pie': faChartPie,
      'fas fa-mouse-pointer': faMousePointer,
      'fas fa-swimming-pool': faSwimmingPool,
      'fas fa-ban': faBan,
      'fas fa-tag': faTag,
      'fas fa-shield': faShield,
      'fas fa-qrcode': faQrcode,
      'fas fa-redo': faRedo,
      'fas fa-ruler': faRuler,
      'fas fa-utensils': faUtensils,
      'fas fa-tshirt': faTshirt,
      'fas fa-sliders-h': faSlidersH,
      'fas fa-glass-whiskey': faGlassWhiskey,
      'fas fa-sort': faSort,
      'fas fa-tachometer-alt': faTachometerAlt,
      'fas fa-spoon': faSpoon,
      'fas fa-store': faStore,
      'fas fa-tablet': faTablet,
      'fas fa-tablet-alt': faTabletAlt,
      'fas fa-thermometer-half': faThermometerHalf,
      'fas fa-bolt': faBolt,
      'fas fa-ticket-alt': faTicketAlt,
      'fas fa-sitemap': faSitemap,
      'fas fa-bath': faBath
    };
    
    // Si está en el mapeo local, úsalo
    if (localIconMap[this.name]) {
      return localIconMap[this.name];
    }
    
    // Si no está en el mapeo local, intenta con findIconDefinition
    let iconName = this.name;
    if (this.name.includes('fas fa-')) {
      iconName = this.name.replace('fas fa-', '');
    } else if (this.name.includes('fa-')) {
      iconName = this.name.replace('fa-', '');
    }
    
    const foundIcon = findIconDefinition({ prefix: 'fas', iconName: iconName as IconName });
    if (foundIcon) {
      return foundIcon;
    }
    
    // Si no se encuentra, retorna undefined
    return undefined;
  }

  get iconClasses(): string {
    const classes = [
      'icon',
      `icon-${this.size}`
    ];
    return classes.filter(Boolean).join(' ');
  }

  get iconStyles(): { [key: string]: string } {
    return {
      'color': this.color
    };
  }
}
