import { EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export type CheckboxSize = 'sm' | 'md' | 'lg';
export type CheckboxStatus = 'default' | 'success' | 'error';
export declare class SaCheckboxComponent implements ControlValueAccessor {
    checked: boolean;
    size: CheckboxSize;
    status: CheckboxStatus;
    label: string;
    private _noLabel;
    set noLabel(value: boolean | any);
    get noLabel(): boolean;
    private _hideLabel;
    set hideLabel(value: boolean | any);
    get hideLabel(): boolean;
    helperText: string;
    errorText: string;
    required: boolean;
    disabled: boolean;
    readonly: boolean;
    id: string;
    name: string;
    value: string;
    indeterminate: boolean;
    bold: boolean;
    class: string;
    checkedChange: EventEmitter<boolean>;
    change: EventEmitter<Event>;
    focusin: EventEmitter<FocusEvent>;
    focusout: EventEmitter<FocusEvent>;
    isFocused: boolean;
    private _generatedId;
    private onChange;
    private onTouched;
    get hostClasses(): string;
    constructor();
    get checkboxId(): string;
    get checkboxClasses(): string;
    get labelClasses(): string;
    get shouldShowLabel(): boolean;
    get containerClasses(): string;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    onCheckboxChange(event: Event): void;
    onCheckboxFocus(event: FocusEvent): void;
    onCheckboxBlur(event: FocusEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SaCheckboxComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SaCheckboxComponent, "sa-checkbox", never, { "checked": { "alias": "checked"; "required": false; }; "size": { "alias": "size"; "required": false; }; "status": { "alias": "status"; "required": false; }; "label": { "alias": "label"; "required": false; }; "noLabel": { "alias": "noLabel"; "required": false; }; "hideLabel": { "alias": "hideLabel"; "required": false; }; "helperText": { "alias": "helperText"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "id": { "alias": "id"; "required": false; }; "name": { "alias": "name"; "required": false; }; "value": { "alias": "value"; "required": false; }; "indeterminate": { "alias": "indeterminate"; "required": false; }; "bold": { "alias": "bold"; "required": false; }; "class": { "alias": "class"; "required": false; }; }, { "checkedChange": "checkedChange"; "change": "change"; "focusin": "focusin"; "focusout": "focusout"; }, never, never, false, never>;
}
