import { Component, Input } from '@angular/core';
import { IconDefinition, findIconDefinition, IconName } from '@fortawesome/fontawesome-svg-core';
import { 
  faSpinner, 
  faDownload, 
  faTrash, 
  faShare, 
  faPrint, 
  faHeart,
  faHome,
  faUser,
  faCog,
  faSearch,
  faStar,
  faEdit,
  faSave,
  faPlus,
  faMinus,
  faCheck,
  faTimes,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendar,
  faClock,
  faInfo,
  faExclamationTriangle,
  faQuestion,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faPencil,
  // Nuevos iconos agregados
  faThLarge,
  faUsers,
  faLink,
  faCopy,
  faUniversalAccess,
  faRunning,
  faImage,
  faCalendarAlt,
  faChartBar,
  faChartLine,
  faAppleAlt,
  faRobot,
  faGift,
  faShoppingBag,
  faBalanceScale,
  faBatteryThreeQuarters,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faBellSlash,
  faBicycle,
  faBookmark,
  faBowlFood,
  faBox,
  faBus,
  faBirthdayCake,
  faCalculator,
  faCalendarDay,
  faCamera,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faFile,
  faChartPie,
  faComments,
  faFlask,
  faMicroscope,
  faCookieBite,
  faSprayCan,
  faSoap,
  faExpand,
  faCloud,
  faCoffee,
  faComment,
  faCreditCard,
  faCrop,
  faCropAlt,
  faTruck,
  faFileUpload,
  faEllipsisH,
  faPlane,
  faGraduationCap,
  faEquals,
  faEraser,
  faFileExcel,
  faFileDownload,
  faSignOutAlt,
  faSmile,
  faFrown,
  faMask,
  faMedal,
  faBoxOpen,
  faSeedling,
  faFilter,
  faFingerprint,
  faFire,
  faTrophy,
  faFish,
  faFlag,
  faForward,
  faVolumeUp,
  faExpandArrowsAlt,
  faGlobe,
  faVolumeMute,
  faBars,
  faBriefcase,
  faMicrochip,
  faHeartbeat,
  faHistory,
  faMicrophone,
  faIceCream,
  faLightbulb,
  faKey,
  faLaptop,
  faLayerGroup,
  faListUl,
  faVolumeDown,
  faMapPin,
  faPills,
  faMobile,
  faMobileAlt,
  faMoneyBill,
  faMotorcycle,
  faStickyNote,
  faEllipsisV,
  faLungs,
  faCashRegister,
  faPaperPlane,
  faPaperclip,
  faDesktop,
  faPause,
  faPercent,
  faPiggyBank,
  faPlay,
  faMousePointer,
  faSwimmingPool,
  faBan,
  faTag,
  faShield,
  faQrcode,
  faReceipt,
  faRedo,
  faRuler,
  faUtensils,
  faTshirt,
  faShoppingCart,
  faSlidersH,
  faGlassWhiskey,
  faSort,
  faTachometerAlt,
  faSpoon,
  faStarHalf,
  faStop,
  faStore,
  faThermometerHalf,
  faThumbsDown,
  faThumbsUp,
  faBolt,
  faTicketAlt,
  faSitemap,
  faBath,
  faUndo,
  faUpload,
  faUserPlus,
  faUserMinus,
  faVideo,
  faExclamationCircle,
  faWifi
} from '@fortawesome/free-solid-svg-icons';

export type IconSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'lib-icon',
  templateUrl: './icon.component.html',
  styleUrl: './icon.component.scss'
})
export class IconComponent {
  @Input() name: string = '';
  @Input() color: string = '#000000';
  @Input() size: IconSize = 'md';

  // Método para obtener el icono basado en el string
  get iconDefinition(): IconDefinition | undefined {
    if (!this.name) return undefined;
    
    // Mapeo local de iconos (más rápido)
    const localIconMap: { [key: string]: IconDefinition } = {
      // Iconos básicos (solid por defecto)
      'spinner': faSpinner,
      'download': faDownload,
      'trash': faTrash,
      'share': faShare,
      'print': faPrint,
      'heart': faHeart,
      'home': faHome,
      'user': faUser,
      'cog': faCog,
      'search': faSearch,
      'star': faStar,
      'edit': faEdit,
      'save': faSave,
      'plus': faPlus,
      'minus': faMinus,
      'check': faCheck,
      'times': faTimes,
      'eye': faEye,
      'eye-slash': faEyeSlash,
      'lock': faLock,
      'unlock': faUnlock,
      'bell': faBell,
      'envelope': faEnvelope,
      'phone': faPhone,
      'map-marker-alt': faMapMarkerAlt,
      'calendar': faCalendar,
      'clock': faClock,
      'info': faInfo,
      'exclamation-triangle': faExclamationTriangle,
      'question': faQuestion,
      'chevron-down': faChevronDown,
      'chevron-up': faChevronUp,
      'chevron-left': faChevronLeft,
      'chevron-right': faChevronRight,
      'arrow-left': faArrowLeft,
      'arrow-right': faArrowRight,
      'arrow-up': faArrowUp,
      'arrow-down': faArrowDown,
      'pencil': faPencil,
      
      // Nuevos iconos agregados
      'cell': faDesktop,
      'grid': faThLarge,
      'group': faUsers,
      'link': faLink,
      'copy': faCopy,
      'accessibility-alt': faUniversalAccess,
      'accessibility': faUniversalAccess,
      'activity': faRunning,
      'add-document': faFile,
      'add-image': faImage,
      'agenda': faCalendarAlt,
      'analytics': faChartBar,
      'analytics-raise': faChartLine,
      'apple': faAppleAlt,
      'assistant': faRobot,
      'bag-of-flour': faGift,
      'bag-with-gift': faGift,
      'bags': faShoppingBag,
      'balance': faBalanceScale,
      'battery-alt': faBatteryThreeQuarters,
      'battery-charginig': faBatteryHalf,
      'battery-full': faBatteryHalf,
      'battery-half': faBatteryHalf,
      'battery-low': faBatteryQuarter,
      'bell-new-message': faBell,
      'bell-off': faBellSlash,
      'bicycle': faBicycle,
      'bookmark-simple': faBookmark,
      'bowl': faBowlFood,
      'box-milk': faBox,
      'bus-front': faBus,
      'butter': faBirthdayCake,
      'cake': faBirthdayCake,
      'calculator': faCalculator,
      'calendar-history-alt': faCalendarDay,
      'calendar-history': faCalendarDay,
      'call-center': faPhone,
      'camera': faCamera,
      'can': faBox,
      'candy': faCookieBite,
      'caret-down': faCaretDown,
      'caret-left': faCaretLeft,
      'caret-right': faCaretRight,
      'caret-up': faCaretUp,
      'cells-document': faFile,
      'chart-bar': faChartBar,
      'chart-pie-slice': faChartPie,
      'chat-circle-text': faComments,
      'chemical-experiment': faFlask,
      'chemical-test': faMicroscope,
      'chocolate-bar': faCookieBite,
      'cleaner': faSprayCan,
      'cleaner-dispenser': faSoap,
      'close-full-screen': faExpand,
      'cloud-offline': faCloud,
      'cloud-problem': faCloud,
      'coffee': faCoffee,
      'comments': faComment,
      'cookie': faCookieBite,
      'credit-card': faCreditCard,
      'crop-alt': faCropAlt,
      'crop': faCrop,
      'crop-health': faCrop,
      'delivery-guy': faTruck,
      'density': faDesktop,
      'detergent': faSoap,
      'document-upload': faFileUpload,
      'dots-three': faEllipsisH,
      'download-alt': faDownload,
      'dron': faPlane,
      'education': faGraduationCap,
      'envelope-new-message': faEnvelope,
      'equals': faEquals,
      'eraser': faEraser,
      'excel': faFileExcel,
      'excel-download': faFileDownload,
      'exit': faSignOutAlt,
      'face-satisfied': faSmile,
      'face-dissatisfied': faFrown,
      'face-mask': faMask,
      'facebook': faShare,
      'fast-truck': faTruck,
      'favorite-calendar': faCalendarAlt,
      'favorite-medal': faMedal,
      'favorite-package': faBoxOpen,
      'feeder': faSeedling,
      'file-download': faFileDownload,
      'filter': faFilter,
      'fingerprint': faFingerprint,
      'fire': faFire,
      'fireworks': faFire,
      'first-place': faTrophy,
      'fish': faFish,
      'flag': faFlag,
      'forward': faForward,
      'full-volume': faVolumeUp,
      'full-screen': faExpandArrowsAlt,
      'gear': faCog,
      'gift': faGift,
      'gift-delivery': faGift,
      'globe': faGlobe,
      'group-bigger': faUsers,
      'half-volume': faVolumeMute,
      'hamburger': faBars,
      'handbag': faBriefcase,
      'happy-chip': faMicrochip,
      'healthy': faHeartbeat,
      'history-time': faHistory,
      'hydrophone': faMicrophone,
      'ice-cream': faIceCream,
      'idea': faLightbulb,
      'identification': faKey,
      'instagram': faShare,
      'intelligence-a-i': faRobot,
      'laptop': faLaptop,
      'layer': faLayerGroup,
      'list-bulleted': faListUl,
      'load-balancer-classic': faDesktop,
      'low-volume': faVolumeDown,
      'machine-learning-model': faRobot,
      'magnifying-glass': faSearch,
      'map': faMapPin,
      'map-pin': faMapPin,
      'medal': faMedal,
      'medicine-alert': faExclamationTriangle,
      'medicine': faPills,
      'micro-chip-alt': faMicrochip,
      'micro-chip': faMicrochip,
      'microscope': faMicroscope,
      'mobile-horizontal': faMobile,
      'mobile-vertical': faMobileAlt,
      'money': faMoneyBill,
      'motorcycle': faMotorcycle,
      'note-pencil': faStickyNote,
      'openlock': faUnlock,
      'overflow-menu-vertical': faEllipsisV,
      'oxygen': faLungs,
      'p-o-s': faCashRegister,
      'package': faBox,
      'package-delay': faBox,
      'paper-plane-right': faPaperPlane,
      'paperclip': faPaperclip,
      'parallel-screen': faDesktop,
      'password': faKey,
      'pause': faPause,
      'percent': faPercent,
      'personal-a-enda': faCalendarAlt,
      'phone-incoming': faPhone,
      'phone-outgoing': faPhone,
      'piggy-bank': faPiggyBank,
      'pill': faPills,
      'place-location': faMapMarkerAlt,
      'play': faPlay,
      'pointer': faMousePointer,
      'pointer-lock': faMousePointer,
      'pool-ladder': faSwimmingPool,
      'post-history': faHistory,
      'postit': faStickyNote,
      'prohibit': faBan,
      'promotion': faTag,
      'protection-checked': faShield,
      'qr': faQrcode,
      'receipt': faReceipt,
      'receipt-checked': faReceipt,
      'reminder-a-enda': faCalendarAlt,
      'renew': faRedo,
      'repeat': faRedo,
      'repeat-purchase': faRedo,
      'ruc': faUser,
      'ruler-alt': faRuler,
      'sauce': faUtensils,
      'scan': faQrcode,
      'search-layers': faSearch,
      'sensor': faMicrochip,
      'settings-alt': faCog,
      'share-network': faShare,
      'shirt': faTshirt,
      'shopping-cart': faShoppingCart,
      'shrimp': faFish,
      'sign-out': faSignOutAlt,
      'sliders-horizontal': faSlidersH,
      'soda': faGlassWhiskey,
      'sort-by': faSort,
      'soup-dispenser': faUtensils,
      'soup-noodles': faUtensils,
      'speedometer': faTachometerAlt,
      'sponge': faSpoon,
      'star-half': faStarHalf,
      'stop': faStop,
      'storefront': faStore,
      'styling-cream': faSoap,
      'substract-volume': faVolumeMute,
      'tablet-horizontal': faDesktop,
      'tablet-vertical': faDesktop,
      'temperature': faThermometerHalf,
      'thumbs-down': faThumbsDown,
      'thumbs-up': faThumbsUp,
      'thunder': faBolt,
      'ticket': faTicketAlt,
      'toothpaste': faSoap,
      'tree-view': faSitemap,
      'trend-down': faChartLine,
      'trend-up': faChartLine,
      'trophy': faTrophy,
      'truck': faTruck,
      'tub': faBath,
      'twitter': faShare,
      'undo': faUndo,
      'upload': faUpload,
      'user-avatar': faUser,
      'user-add': faUserPlus,
      'user-substract': faUserMinus,
      'user-with-cart': faUser,
      'video-layer': faVideo,
      'warning-circle': faExclamationCircle,
      'warning-triangle': faExclamationTriangle,
      'whatsapp': faShare,
      'wi-fi': faWifi,
      'wi-fi-off': faWifi,
      'x': faTimes,
      'youtube': faShare,
      
      // También soporta formato fas fa-
      'fas fa-spinner': faSpinner,
      'fas fa-download': faDownload,
      'fas fa-trash': faTrash,
      'fas fa-share': faShare,
      'fas fa-print': faPrint,
      'fas fa-heart': faHeart,
      'fas fa-home': faHome,
      'fas fa-user': faUser,
      'fas fa-cog': faCog,
      'fas fa-search': faSearch,
      'fas fa-star': faStar,
      'fas fa-edit': faEdit,
      'fas fa-save': faSave,
      'fas fa-plus': faPlus,
      'fas fa-minus': faMinus,
      'fas fa-check': faCheck,
      'fas fa-times': faTimes,
      'fas fa-eye': faEye,
      'fas fa-eye-slash': faEyeSlash,
      'fas fa-lock': faLock,
      'fas fa-unlock': faUnlock,
      'fas fa-bell': faBell,
      'fas fa-envelope': faEnvelope,
      'fas fa-phone': faPhone,
      'fas fa-map-marker-alt': faMapMarkerAlt,
      'fas fa-calendar': faCalendar,
      'fas fa-clock': faClock,
      'fas fa-info': faInfo,
      'fas fa-exclamation-triangle': faExclamationTriangle,
      'fas fa-question': faQuestion,
      'fas fa-chevron-down': faChevronDown,
      'fas fa-chevron-up': faChevronUp,
      'fas fa-chevron-left': faChevronLeft,
      'fas fa-chevron-right': faChevronRight,
      'fas fa-arrow-left': faArrowLeft,
      'fas fa-arrow-right': faArrowRight,
      'fas fa-arrow-up': faArrowUp,
      'fas fa-arrow-down': faArrowDown,
      'fas fa-pencil': faPencil
    };
    
    // Si está en el mapeo local, úsalo
    if (localIconMap[this.name]) {
      return localIconMap[this.name];
    }
    
    // Si no está en el mapeo local, intenta con findIconDefinition
    let iconName = this.name;
    if (this.name.includes('fas fa-')) {
      iconName = this.name.replace('fas fa-', '');
    } else if (this.name.includes('fa-')) {
      iconName = this.name.replace('fa-', '');
    }
    
    const foundIcon = findIconDefinition({ prefix: 'fas', iconName: iconName as IconName });
    if (foundIcon) {
      return foundIcon;
    }
    
    // Si no se encuentra, retorna undefined
    return undefined;
  }

  get iconClasses(): string {
    const classes = [
      'icon',
      `icon-${this.size}`
    ];
    return classes.filter(Boolean).join(' ');
  }

  get iconStyles(): { [key: string]: string } {
    return {
      'color': this.color
    };
  }
}
