import { EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export type InputType = 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' | 'search' | 'date' | 'time' | 'datetime-local';
export type InputSize = 'small' | 'medium' | 'large';
export type InputVariant = 'default' | 'success' | 'warning' | 'error';
export declare class SaInputComponent implements ControlValueAccessor {
    placeholder: string;
    type: InputType;
    size: InputSize;
    variant: InputVariant;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    name: string;
    id: string;
    maxlength?: number;
    minlength?: number;
    pattern?: string;
    autocomplete?: string;
    label?: string;
    helperText?: string;
    errorText?: string;
    showPasswordToggle: boolean;
    leftIcon?: string;
    rightIcon?: string;
    valueChange: EventEmitter<string>;
    focus: EventEmitter<FocusEvent>;
    blur: EventEmitter<FocusEvent>;
    input: EventEmitter<Event>;
    value: string;
    showPassword: boolean;
    isFocused: boolean;
    private onChange;
    private onTouched;
    writeValue(value: string): void;
    registerOnChange(fn: (value: string) => void): void;
    registerOnTouched(fn: () => void): void;
    setDisabledState(isDisabled: boolean): void;
    onInput(event: Event): void;
    onFocus(event: FocusEvent): void;
    onBlur(event: FocusEvent): void;
    togglePasswordVisibility(): void;
    get inputType(): string;
    get inputClasses(): string;
    get hasError(): boolean;
    get showPasswordToggleButton(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<SaInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SaInputComponent, "sa-input", never, { "placeholder": { "alias": "placeholder"; "required": false; }; "type": { "alias": "type"; "required": false; }; "size": { "alias": "size"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "required": { "alias": "required"; "required": false; }; "name": { "alias": "name"; "required": false; }; "id": { "alias": "id"; "required": false; }; "maxlength": { "alias": "maxlength"; "required": false; }; "minlength": { "alias": "minlength"; "required": false; }; "pattern": { "alias": "pattern"; "required": false; }; "autocomplete": { "alias": "autocomplete"; "required": false; }; "label": { "alias": "label"; "required": false; }; "helperText": { "alias": "helperText"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "showPasswordToggle": { "alias": "showPasswordToggle"; "required": false; }; "leftIcon": { "alias": "leftIcon"; "required": false; }; "rightIcon": { "alias": "rightIcon"; "required": false; }; }, { "valueChange": "valueChange"; "focus": "focus"; "blur": "blur"; "input": "input"; }, never, never, false, never>;
}
