import { EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export type DateSize = 'sm' | 'md' | 'lg';
export type DateStatus = 'default' | 'success' | 'error';
export declare class SaDateComponent implements ControlValueAccessor, OnInit {
    value: string;
    size: DateSize;
    status: DateStatus;
    label: string;
    placeholder: string;
    helperText: string;
    errorText: string;
    required: boolean;
    readonly: boolean;
    disabled: boolean;
    id: string;
    name: string;
    min: string;
    max: string;
    blockFutureDates: boolean;
    showCurrentDate: boolean;
    valueChange: EventEmitter<string>;
    focus: EventEmitter<FocusEvent>;
    blur: EventEmitter<FocusEvent>;
    isFocused: boolean;
    private _generatedId;
    private onChange;
    private onTouched;
    constructor();
    ngOnInit(): void;
    get dateId(): string;
    get inputClasses(): string;
    get labelClasses(): string;
    private getCurrentDateISO;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    onModelChange(value: string): void;
    onInputFocus(event: FocusEvent): void;
    onInputBlur(event: FocusEvent): void;
    openCalendar(event: MouseEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SaDateComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SaDateComponent, "sa-date", never, { "value": { "alias": "value"; "required": false; }; "size": { "alias": "size"; "required": false; }; "status": { "alias": "status"; "required": false; }; "label": { "alias": "label"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "helperText": { "alias": "helperText"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "id": { "alias": "id"; "required": false; }; "name": { "alias": "name"; "required": false; }; "min": { "alias": "min"; "required": false; }; "max": { "alias": "max"; "required": false; }; "blockFutureDates": { "alias": "blockFutureDates"; "required": false; }; "showCurrentDate": { "alias": "showCurrentDate"; "required": false; }; }, { "valueChange": "valueChange"; "focus": "focus"; "blur": "blur"; }, never, never, false, never>;
}
